//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vypr.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vypr.Shared.Resources.ApplicationText", typeof(ApplicationText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Photos.
        /// </summary>
        public static string AdditionalPhotos {
            get {
                return ResourceManager.GetString("AdditionalPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API IP whitelist.
        /// </summary>
        public static string ApiIpWhitelist {
            get {
                return ResourceManager.GetString("ApiIpWhitelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API key has already been generated, and for security purposes is no longer visible. If required, a new API key can be generated. The former API key will no longer work..
        /// </summary>
        public static string ApiKeyExistsDescription {
            get {
                return ResourceManager.GetString("ApiKeyExistsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string ApiKeyGenerate {
            get {
                return ResourceManager.GetString("ApiKeyGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates the API key for tenant. This will allow users with the appropriate role to make API calls. For security purposes, this API Key will only be visible on generation and will not be accessible again..
        /// </summary>
        public static string ApiKeyGenerateDescription {
            get {
                return ResourceManager.GetString("ApiKeyGenerateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key is hidden.
        /// </summary>
        public static string ApiKeyHidden {
            get {
                return ResourceManager.GetString("ApiKeyHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key is invalid or is not correctly configured in the system.
        /// </summary>
        public static string ApiKeyInvalid {
            get {
                return ResourceManager.GetString("ApiKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For security purposes, this API Key will only be visible on generation and will not be accessible again. If this key is forgotten or lost, a new API Key can be generated, and the former key will no longer function..
        /// </summary>
        public static string ApiKeyIsGeneratedDescription {
            get {
                return ResourceManager.GetString("ApiKeyIsGeneratedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key is required.
        /// </summary>
        public static string ApiKeyRequired {
            get {
                return ResourceManager.GetString("ApiKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API User.
        /// </summary>
        public static string ApiUser {
            get {
                return ResourceManager.GetString("ApiUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        public static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Delivery.
        /// </summary>
        public static string CompleteDelivery {
            get {
                return ResourceManager.GetString("CompleteDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Trips.
        /// </summary>
        public static string CompletedTrips {
            get {
                return ResourceManager.GetString("CompletedTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm delivery details.
        /// </summary>
        public static string ConfirmDeliveryDetails {
            get {
                return ResourceManager.GetString("ConfirmDeliveryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm rejection details.
        /// </summary>
        public static string ConfirmRejectionDetails {
            get {
                return ResourceManager.GetString("ConfirmRejectionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Details.
        /// </summary>
        public static string ConnectionDetails {
            get {
                return ResourceManager.GetString("ConnectionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not establish remote IP address.
        /// </summary>
        public static string CouldNotEstablishRemoteIp {
            get {
                return ResourceManager.GetString("CouldNotEstablishRemoteIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CounterAct Key.
        /// </summary>
        public static string CounterActKey {
            get {
                return ResourceManager.GetString("CounterActKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Counteract API Key for the tenant. This is the security key used in conjuction with the CountAct API Url to gain access to the resource..
        /// </summary>
        public static string CounterActKeyDescription {
            get {
                return ResourceManager.GetString("CounterActKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CounterAct Settings.
        /// </summary>
        public static string CounterActSettings {
            get {
                return ResourceManager.GetString("CounterActSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine CounterAct version from the configured API URL. There was no endpoint listening at this address that could accept the versioning request. This is often caused by an incorrect address or SOAP action..
        /// </summary>
        public static string CounterActUnknownVersion {
            get {
                return ResourceManager.GetString("CounterActUnknownVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CounterAct API Url.
        /// </summary>
        public static string CounterActUrl {
            get {
                return ResourceManager.GetString("CounterActUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CounterAct API Url for the tenant. This is the origin used to build the endpoints when retrieving and updating delivery data. .
        /// </summary>
        public static string CounterActUrlDescription {
            get {
                return ResourceManager.GetString("CounterActUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CounterAct version.
        /// </summary>
        public static string CounterActVersionAt {
            get {
                return ResourceManager.GetString("CounterActVersionAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Driver Role.
        /// </summary>
        public static string DefaultDriverRole {
            get {
                return ResourceManager.GetString("DefaultDriverRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliver via.
        /// </summary>
        public static string DeliverVia {
            get {
                return ResourceManager.GetString("DeliverVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave any comments here....
        /// </summary>
        public static string DropCommentPlaceholder {
            get {
                return ResourceManager.GetString("DropCommentPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Off.
        /// </summary>
        public static string DropOff {
            get {
                return ResourceManager.GetString("DropOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Off Location.
        /// </summary>
        public static string DropOffLocation {
            get {
                return ResourceManager.GetString("DropOffLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup.
        /// </summary>
        public static string DropPickup {
            get {
                return ResourceManager.GetString("DropPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup Location.
        /// </summary>
        public static string DropPickupLocation {
            get {
                return ResourceManager.GetString("DropPickupLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave any rejection comments here....
        /// </summary>
        public static string DropRejectionCommentPlaceholder {
            get {
                return ResourceManager.GetString("DropRejectionCommentPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejection comment required in order to complete this delivery.
        /// </summary>
        public static string DropRejectionCommentRequired {
            get {
                return ResourceManager.GetString("DropRejectionCommentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drops.
        /// </summary>
        public static string Drops {
            get {
                return ResourceManager.GetString("Drops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ability to administer Drops.
        /// </summary>
        public static string Drops_Administer {
            get {
                return ResourceManager.GetString("Drops_Administer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ability to read Drops.
        /// </summary>
        public static string Drops_Read {
            get {
                return ResourceManager.GetString("Drops_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This drop has been done and marked as &lt;b&gt;completed.&lt;/b&gt;.
        /// </summary>
        public static string DropStatusCompleted {
            get {
                return ResourceManager.GetString("DropStatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This drop has been done and marked as &lt;b&gt;rejected.&lt;/b&gt;.
        /// </summary>
        public static string DropStatusRejected {
            get {
                return ResourceManager.GetString("DropStatusRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Maps API Key.
        /// </summary>
        public static string GoogleMapApiKey {
            get {
                return ResourceManager.GetString("GoogleMapApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configures the Google Maps API key for the tenant. This will enable Google maps
        ///                        to be embedded in the Driver user interface when carrying out deliveries..
        /// </summary>
        public static string GoogleMapApiKeyDescription {
            get {
                return ResourceManager.GetString("GoogleMapApiKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to continue without waiting? If you choose to complete the delivery now, any images which have not finished uploading will be lost..
        /// </summary>
        public static string ImageUploadWait {
            get {
                return ResourceManager.GetString("ImageUploadWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid IPv4 format..
        /// </summary>
        public static string IpAddressBadFormat {
            get {
                return ResourceManager.GetString("IpAddressBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An IP address cannot be empty..
        /// </summary>
        public static string IpAddressCannotBeEmpty {
            get {
                return ResourceManager.GetString("IpAddressCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorised to complete this request.
        /// </summary>
        public static string IpAddressUnauthorized {
            get {
                return ResourceManager.GetString("IpAddressUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently no API key configured for this tenant. Any requests to the API resource will therefore be blocked. You must configure an API key here and add it to your HTTP requests header section to authenticate with the API..
        /// </summary>
        public static string NoApiKeyConfigured {
            get {
                return ResourceManager.GetString("NoApiKeyConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Comment Entered.
        /// </summary>
        public static string NoCommentEntered {
            get {
                return ResourceManager.GetString("NoCommentEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No default driver role set up for tenant.
        /// </summary>
        public static string NoDefaultDriverRole {
            get {
                return ResourceManager.GetString("NoDefaultDriverRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available drops to show.
        /// </summary>
        public static string NoDropsToShow {
            get {
                return ResourceManager.GetString("NoDropsToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available trips to show.
        /// </summary>
        public static string NoTripsToShow {
            get {
                return ResourceManager.GetString("NoTripsToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string NoUserFound {
            get {
                return ResourceManager.GetString("NoUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use photo.
        /// </summary>
        public static string OptionOfPhoto {
            get {
                return ResourceManager.GetString("OptionOfPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use signature.
        /// </summary>
        public static string OptionOfSignature {
            get {
                return ResourceManager.GetString("OptionOfSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To complete the delivery please upload photographic evidence or request a signature..
        /// </summary>
        public static string PhotoEvidence {
            get {
                return ResourceManager.GetString("PhotoEvidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photographic evidence is required before completing this delivery.
        /// </summary>
        public static string PhotoEvidenceRequired {
            get {
                return ResourceManager.GetString("PhotoEvidenceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof of delivery options.
        /// </summary>
        public static string ProofOfDeliveryOptions {
            get {
                return ResourceManager.GetString("ProofOfDeliveryOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for rejection:.
        /// </summary>
        public static string ReasonForRejection {
            get {
                return ResourceManager.GetString("ReasonForRejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient name: .
        /// </summary>
        public static string RecipientName {
            get {
                return ResourceManager.GetString("RecipientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient signature.
        /// </summary>
        public static string RecipientSignature {
            get {
                return ResourceManager.GetString("RecipientSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Delivery.
        /// </summary>
        public static string RejectDelivery {
            get {
                return ResourceManager.GetString("RejectDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Drops.
        /// </summary>
        public static string RejectedDrops {
            get {
                return ResourceManager.GetString("RejectedDrops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To reject the delivery please upload photographic evidence or request a signature..
        /// </summary>
        public static string RejectPhotoEvidence {
            get {
                return ResourceManager.GetString("RejectPhotoEvidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string RequirePhoto {
            get {
                return ResourceManager.GetString("RequirePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string RequireSignature {
            get {
                return ResourceManager.GetString("RequireSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Photos.
        /// </summary>
        public static string SelectPhotos {
            get {
                return ResourceManager.GetString("SelectPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign here.
        /// </summary>
        public static string SignaturePlaceholder {
            get {
                return ResourceManager.GetString("SignaturePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer signature is required before completing this delivery.
        /// </summary>
        public static string SignatureRequired {
            get {
                return ResourceManager.GetString("SignatureRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Image Upload.
        /// </summary>
        public static string SkipImageAttachments {
            get {
                return ResourceManager.GetString("SkipImageAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ability to administer Tenant Connection Details.
        /// </summary>
        public static string Tenant_ConnectionDetails_Administer {
            get {
                return ResourceManager.GetString("Tenant_ConnectionDetails_Administer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No IP Address constraint.
        /// </summary>
        public static string TenantApiIpAddressEmpty {
            get {
                return ResourceManager.GetString("TenantApiIpAddressEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently no IP address constraint configured for this tenants access to the API - this means any IP addresses are granted access providing they present the correct API key. It is recommended for security purposes you add the IP addresses that will be exclusively accessing this resource. .
        /// </summary>
        public static string TenantApiIpAddressNoConstraints {
            get {
                return ResourceManager.GetString("TenantApiIpAddressNoConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add IP address due to an internal server error..
        /// </summary>
        public static string TenantApiIpCouldNotAdd {
            get {
                return ResourceManager.GetString("TenantApiIpCouldNotAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove IP address due to an internal server error..
        /// </summary>
        public static string TenantApiIpCouldNotDelete {
            get {
                return ResourceManager.GetString("TenantApiIpCouldNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisational tenant is not properly configured to establish a connection to a resource..
        /// </summary>
        public static string TenantBadConfiguration {
            get {
                return ResourceManager.GetString("TenantBadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo.
        /// </summary>
        public static string Todo {
            get {
                return ResourceManager.GetString("Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string Tomorrrow {
            get {
                return ResourceManager.GetString("Tomorrrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Progress.
        /// </summary>
        public static string TripProgress {
            get {
                return ResourceManager.GetString("TripProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trips.
        /// </summary>
        public static string Trips {
            get {
                return ResourceManager.GetString("Trips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ability to administer Trips.
        /// </summary>
        public static string Trips_Administer {
            get {
                return ResourceManager.GetString("Trips_Administer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ability to read Trips.
        /// </summary>
        public static string Trips_Read {
            get {
                return ResourceManager.GetString("Trips_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trips Dashboard.
        /// </summary>
        public static string TripsDashboard {
            get {
                return ResourceManager.GetString("TripsDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error obtaining trip information from the server.
        /// </summary>
        public static string TripsRemoteApiError {
            get {
                return ResourceManager.GetString("TripsRemoteApiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow&apos;s Trips.
        /// </summary>
        public static string TripsTomorrow {
            get {
                return ResourceManager.GetString("TripsTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Connections.
        /// </summary>
        public static string UpdateConnectionDetails {
            get {
                return ResourceManager.GetString("UpdateConnectionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update key.
        /// </summary>
        public static string UpdateKey {
            get {
                return ResourceManager.GetString("UpdateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Photo.
        /// </summary>
        public static string UploadPhoto {
            get {
                return ResourceManager.GetString("UploadPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created by API feed, therefore some properties may be unavailable for modification..
        /// </summary>
        public static string UserIsDataFed {
            get {
                return ResourceManager.GetString("UserIsDataFed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View direct drop.
        /// </summary>
        public static string ViewDirectDrop {
            get {
                return ResourceManager.GetString("ViewDirectDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View drop.
        /// </summary>
        public static string ViewDrop {
            get {
                return ResourceManager.GetString("ViewDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View trip.
        /// </summary>
        public static string ViewTrip {
            get {
                return ResourceManager.GetString("ViewTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What3Words API Key.
        /// </summary>
        public static string WhatThreeWordsApiKey {
            get {
                return ResourceManager.GetString("WhatThreeWordsApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configures the What3Words API key for the tenant. This will enable What3Words to be used instead of GPS coordinates with maps in the Driver user interface when carrying out deliveries..
        /// </summary>
        public static string WhatThreeWordsApiKeyDescription {
            get {
                return ResourceManager.GetString("WhatThreeWordsApiKeyDescription", resourceCulture);
            }
        }
    }
}
