//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VyprCore.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StandardText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StandardText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VyprCore.Models.Resources.StandardText", typeof(StandardText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api.
        /// </summary>
        public static string Api {
            get {
                return ResourceManager.GetString("Api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is running offline.
        /// </summary>
        public static string ApplicationRunningOffline {
            get {
                return ResourceManager.GetString("ApplicationRunningOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update entity as the model does not conform to internal constraints.
        /// </summary>
        public static string BadModelConformity {
            get {
                return ResourceManager.GetString("BadModelConformity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulletins.
        /// </summary>
        public static string Bulletins {
            get {
                return ResourceManager.GetString("Bulletins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete role/s?.
        /// </summary>
        public static string ConfirmDeleteRoleMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteRoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete user/s?.
        /// </summary>
        public static string ConfirmDeleteUserMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to send user an email invitation? This allows the user to create credentials to gain access to the system..
        /// </summary>
        public static string ConfirmSendUserInvite {
            get {
                return ResourceManager.GetString("ConfirmSendUserInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Email.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Phone Number.
        /// </summary>
        public static string ContactNumber {
            get {
                return ResourceManager.GetString("ContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Role.
        /// </summary>
        public static string CreateANewRole {
            get {
                return ResourceManager.GetString("CreateANewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New User.
        /// </summary>
        public static string CreateANewUser {
            get {
                return ResourceManager.GetString("CreateANewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Role.
        /// </summary>
        public static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default role for driver has been changed.
        /// </summary>
        public static string DefaultDriverRoleChanged {
            get {
                return ResourceManager.GetString("DefaultDriverRoleChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Mode - Data may be periodically reset.
        /// </summary>
        public static string DevelopmentBanner {
            get {
                return ResourceManager.GetString("DevelopmentBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email already exists against a registered user in the system. Please use a different email..
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Id.
        /// </summary>
        public static string ExternalId {
            get {
                return ResourceManager.GetString("ExternalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected more files than the maximum allowed. .
        /// </summary>
        public static string FileSelectionCountExceeds {
            get {
                return ResourceManager.GetString("FileSelectionCountExceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your selection exceeds the number of maximum number of files allowed. Please remove some file/s before trying again..
        /// </summary>
        public static string FileSelectionCountExceeds2 {
            get {
                return ResourceManager.GetString("FileSelectionCountExceeds2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected a file which exceeds than the maximum allowed size..
        /// </summary>
        public static string FileSelectionSizeExceeds {
            get {
                return ResourceManager.GetString("FileSelectionSizeExceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login, you may have entered an invalid username or password. If you continue to see this error contact your web administrator for support.
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve a value from the resource..
        /// </summary>
        public static string LocalisationFailed {
            get {
                return ResourceManager.GetString("LocalisationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t currently have permission to perform this action.
        /// </summary>
        public static string MissingPermission {
            get {
                return ResourceManager.GetString("MissingPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebAuthn has not been setup for this user or device. Please login first to be prompted..
        /// </summary>
        public static string MissingWebAuthnCredentials {
            get {
                return ResourceManager.GetString("MissingWebAuthnCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name the role and choose active status.
        /// </summary>
        public static string NameRole {
            get {
                return ResourceManager.GetString("NameRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records to display..
        /// </summary>
        public static string NoRecordsToDisplay {
            get {
                return ResourceManager.GetString("NoRecordsToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not have an email registered to their account.
        /// </summary>
        public static string NoUserEmailExists {
            get {
                return ResourceManager.GetString("NoUserEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Users to display.
        /// </summary>
        public static string NoUsers {
            get {
                return ResourceManager.GetString("NoUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Management.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ability to create roles.
        /// </summary>
        public static string Role_Create {
            get {
                return ResourceManager.GetString("Role_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ability to delete roles.
        /// </summary>
        public static string Role_Delete {
            get {
                return ResourceManager.GetString("Role_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ability to view roles.
        /// </summary>
        public static string Role_Read {
            get {
                return ResourceManager.GetString("Role_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ability to edit roles.
        /// </summary>
        public static string Role_Update {
            get {
                return ResourceManager.GetString("Role_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Role by that name already exists.
        /// </summary>
        public static string RoleAlreadyExists {
            get {
                return ResourceManager.GetString("RoleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Claims.
        /// </summary>
        public static string RoleClaims {
            get {
                return ResourceManager.GetString("RoleClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ability to administer role claims for roles.
        /// </summary>
        public static string RoleClaims_Administer {
            get {
                return ResourceManager.GetString("RoleClaims_Administer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ability to view role claims.
        /// </summary>
        public static string RoleClaims_Read {
            get {
                return ResourceManager.GetString("RoleClaims_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role claims successfully applied.
        /// </summary>
        public static string RoleClaimsUpdated {
            get {
                return ResourceManager.GetString("RoleClaimsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role has been successfully created.
        /// </summary>
        public static string RoleCreated {
            get {
                return ResourceManager.GetString("RoleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role has been deleted.
        /// </summary>
        public static string RoleDeleted {
            get {
                return ResourceManager.GetString("RoleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Details.
        /// </summary>
        public static string RoleDetails {
            get {
                return ResourceManager.GetString("RoleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Type.
        /// </summary>
        public static string RoleType {
            get {
                return ResourceManager.GetString("RoleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Role.
        /// </summary>
        public static string SelectRole {
            get {
                return ResourceManager.GetString("SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send User Invitation.
        /// </summary>
        public static string SendUserInvite {
            get {
                return ResourceManager.GetString("SendUserInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styling File.
        /// </summary>
        public static string StylingFile {
            get {
                return ResourceManager.GetString("StylingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ability to access Swagger.
        /// </summary>
        public static string Swagger_Administer {
            get {
                return ResourceManager.GetString("Swagger_Administer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a user with ID.
        /// </summary>
        public static string UnableToFindUserWithId {
            get {
                return ResourceManager.GetString("UnableToFindUserWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process your request.
        /// </summary>
        public static string UnableToProcessRequest {
            get {
                return ResourceManager.GetString("UnableToProcessRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Details.
        /// </summary>
        public static string UpdateDetails {
            get {
                return ResourceManager.GetString("UpdateDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ability to create users.
        /// </summary>
        public static string User_Create {
            get {
                return ResourceManager.GetString("User_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ability to delete users.
        /// </summary>
        public static string User_Delete {
            get {
                return ResourceManager.GetString("User_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ability to view users.
        /// </summary>
        public static string User_Read {
            get {
                return ResourceManager.GetString("User_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send users invitiation emails from user management screen..
        /// </summary>
        public static string User_SendInvitation {
            get {
                return ResourceManager.GetString("User_SendInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ability to edit users.
        /// </summary>
        public static string User_Update {
            get {
                return ResourceManager.GetString("User_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has successfully been created.
        /// </summary>
        public static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been deleted.
        /// </summary>
        public static string UserDeleted {
            get {
                return ResourceManager.GetString("UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user delete operation encountered an unexpected error.
        /// </summary>
        public static string UserDeleteOperationError {
            get {
                return ResourceManager.GetString("UserDeleteOperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deleted a user which has an association to another tenant..
        /// </summary>
        public static string UserDeleteOperationErrorUserTenant {
            get {
                return ResourceManager.GetString("UserDeleteOperationErrorUserTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        public static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is inactive.
        /// </summary>
        public static string UserInactive {
            get {
                return ResourceManager.GetString("UserInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation has been sent to the user.
        /// </summary>
        public static string UserInviteSent {
            get {
                return ResourceManager.GetString("UserInviteSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username already exists against a registered user in the system. Please use a different username..
        /// </summary>
        public static string UserNameAlreadyExsists {
            get {
                return ResourceManager.GetString("UserNameAlreadyExsists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Roles.
        /// </summary>
        public static string UserRoles {
            get {
                return ResourceManager.GetString("UserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User roles have successfully been updated in the system.
        /// </summary>
        public static string UserRolesUpdated {
            get {
                return ResourceManager.GetString("UserRolesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has successfully been updated in the system.
        /// </summary>
        public static string UserUpdated {
            get {
                return ResourceManager.GetString("UserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network connectivity detected, your action has been queued and will be sent when network connectivity is restored..
        /// </summary>
        public static string WarningOfflineRequestQueued {
            get {
                return ResourceManager.GetString("WarningOfflineRequestQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device verification cancelled or there was an error authenticating.
        /// </summary>
        public static string WebAuthnCancelled {
            get {
                return ResourceManager.GetString("WebAuthnCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to link your account to your device due to either a verification problem or an internal server issue.
        /// </summary>
        public static string WebAuthnCreateCredentialProblem {
            get {
                return ResourceManager.GetString("WebAuthnCreateCredentialProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user does not exist or there was a problem logging you in.
        /// </summary>
        public static string WebAuthnLoginProblem {
            get {
                return ResourceManager.GetString("WebAuthnLoginProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device does not have a &apos;platform&apos; authenticator available and therefore this option cannot be used. Please login with your password instead..
        /// </summary>
        public static string WebAuthnNoAuthenticatorAvailable {
            get {
                return ResourceManager.GetString("WebAuthnNoAuthenticatorAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials verified for device, but could not log in due to not finding a tenant for this origin (URL)..
        /// </summary>
        public static string WebAuthnProblemAfterVerify {
            get {
                return ResourceManager.GetString("WebAuthnProblemAfterVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to link user with device. This may be caused by user cancellation, the operation timing out or user verification using this device is not allowed.
        /// </summary>
        public static string WebAuthnTimeOutOrNotAllowed {
            get {
                return ResourceManager.GetString("WebAuthnTimeOutOrNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to verify user, it may be because this device is not linked to your account yet. Follow the instructions below to do so..
        /// </summary>
        public static string WebAuthnUnableToEstablishVerification {
            get {
                return ResourceManager.GetString("WebAuthnUnableToEstablishVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to verify the ownership of this account. This may be due to an incorrect user/password combination or an internal server-side problem.
        /// </summary>
        public static string WebAuthnVerifyProblem {
            get {
                return ResourceManager.GetString("WebAuthnVerifyProblem", resourceCulture);
            }
        }
    }
}
