// <autogenerated />
// <copyright file="{MANY}.cs" company="Vypr Systems">
// Copyright (c) Vypr Systems. All rights reserved.
// </copyright>

namespace Vypr.Client.Api
{
    using VyprCore.Interfaces.Client;

    /// <summary>
    /// Vyper User.
    /// </summary>
    /// <seealso cref="VyprCore.Interfaces.Client.IApiRoute" />
    public class VyprUserApiRoute : IApiRoute
    {
        public string Route => "users";
    }

    /// <summary>
    /// Vypr Config.
    /// </summary>
    /// <seealso cref="VyprCore.Interfaces.Client.IApiRoute" />
    public class ConfigurationApiRoute : IApiRoute
    {
        public string Route => "configuration";
    }
}
